steps:
  - name: "gcr.io/cloud-builders/gsutil"
    dir: "scripts"
    args: ["-m", "rsync", "-d", "-r", ".", "gs://castello-bizzarro/scripts"]
    env:
      - "CLOUDSDK_CORE_DISABLE_PROMPTS=1"

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "acl", "ch", "-u", "AllUsers:R", "-r", "gs://castello-bizzarro/scripts"]

options:
  logging: CLOUD_LOGGING_ONLY